# Generated by Django 5.0.4 on 2024-06-04 16:20

import ckeditor.fields
import django.db.models.deletion
import utils.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NavLinks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Заголовок')),
                ('title_ru', models.CharField(max_length=100, null=True, verbose_name='Заголовок')),
                ('title_en', models.CharField(max_length=100, null=True, verbose_name='Заголовок')),
                ('title_ky', models.CharField(max_length=100, null=True, verbose_name='Заголовок')),
                ('url', models.URLField(verbose_name='URL')),
            ],
        ),
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500, verbose_name='Оглавление')),
                ('title_ru', models.CharField(max_length=500, null=True, verbose_name='Оглавление')),
                ('title_en', models.CharField(max_length=500, null=True, verbose_name='Оглавление')),
                ('title_ky', models.CharField(max_length=500, null=True, verbose_name='Оглавление')),
                ('text', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('text_ru', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('text_en', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('text_ky', ckeditor.fields.RichTextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Новость',
                'verbose_name_plural': 'Новости',
            },
        ),
        migrations.CreateModel(
            name='Partners',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Имя/Название')),
                ('name_ru', models.CharField(max_length=50, null=True, verbose_name='Имя/Название')),
                ('name_en', models.CharField(max_length=50, null=True, verbose_name='Имя/Название')),
                ('name_ky', models.CharField(max_length=50, null=True, verbose_name='Имя/Название')),
                ('text', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('text_ru', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('text_en', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('text_ky', ckeditor.fields.RichTextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Партнер',
                'verbose_name_plural': 'Партнеры',
            },
        ),
        migrations.CreateModel(
            name='TextContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Заголовок')),
                ('title_ru', models.CharField(max_length=100, null=True, verbose_name='Заголовок')),
                ('title_en', models.CharField(max_length=100, null=True, verbose_name='Заголовок')),
                ('title_ky', models.CharField(max_length=100, null=True, verbose_name='Заголовок')),
                ('description', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('description_ru', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('description_en', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('description_ky', ckeditor.fields.RichTextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Veteran',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Заголовок')),
                ('title_ru', models.CharField(max_length=100, null=True, verbose_name='Заголовок')),
                ('title_en', models.CharField(max_length=100, null=True, verbose_name='Заголовок')),
                ('title_ky', models.CharField(max_length=100, null=True, verbose_name='Заголовок')),
                ('full_name', models.CharField(max_length=150, verbose_name='Полное имя')),
                ('full_name_ru', models.CharField(max_length=150, null=True, verbose_name='Полное имя')),
                ('full_name_en', models.CharField(max_length=150, null=True, verbose_name='Полное имя')),
                ('full_name_ky', models.CharField(max_length=150, null=True, verbose_name='Полное имя')),
                ('rank', models.CharField(blank=True, max_length=100, null=True, verbose_name='Звание')),
                ('rank_ru', models.CharField(blank=True, max_length=100, null=True, verbose_name='Звание')),
                ('rank_en', models.CharField(blank=True, max_length=100, null=True, verbose_name='Звание')),
                ('rank_ky', models.CharField(blank=True, max_length=100, null=True, verbose_name='Звание')),
                ('description', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('description_ru', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('description_en', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('description_ky', ckeditor.fields.RichTextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Ветеран',
                'verbose_name_plural': 'Ветераны',
            },
        ),
        migrations.CreateModel(
            name='NAVImages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', utils.fields.WEBPField(upload_to=utils.fields.image_folder)),
                ('content_text', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='page_generator.navlinks')),
            ],
        ),
        migrations.CreateModel(
            name='NewsImages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', utils.fields.WEBPField(upload_to=utils.fields.image_folder)),
                ('news', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='page_generator.news')),
            ],
        ),
        migrations.CreateModel(
            name='PartnersImages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', utils.fields.WEBPField(upload_to=utils.fields.image_folder)),
                ('partners', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='page_generator.partners')),
            ],
        ),
        migrations.CreateModel(
            name='Images',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', utils.fields.WEBPField(upload_to=utils.fields.image_folder)),
                ('content_text', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='page_generator.textcontent')),
            ],
        ),
        migrations.CreateModel(
            name='VeteransImages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', utils.fields.WEBPField(upload_to=utils.fields.image_folder)),
                ('veterans', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='page_generator.veteran')),
            ],
        ),
    ]
