# Generated by Django 4.2 on 2024-06-05 11:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('page_generator', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='textcontent',
            name='page',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='text_contents', to='page_generator.pagegenerator', verbose_name='Страница'),
        ),
    ]
