# Generated by Django 4.2 on 2024-06-05 12:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('page_generator', '0002_textcontent_page'),
    ]

    operations = [
        migrations.AlterField(
            model_name='navlinks',
            name='page',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='nav_links', to='page_generator.pagegenerator', verbose_name='Страница'),
        ),
        migrations.AlterField(
            model_name='pagegenerator',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='page-generator/', verbose_name='Баннер'),
        ),
        migrations.CreateModel(
            name='ImageContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='page-generator/images', verbose_name='Изображение')),
                ('page', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='images_content', to='page_generator.pagegenerator', verbose_name='Страница')),
            ],
            options={
                'verbose_name': 'Изображение',
                'verbose_name_plural': 'Изображения для страниц',
            },
        ),
        migrations.CreateModel(
            name='Documents',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pdf', models.FileField(upload_to='page-generator/documents', verbose_name='Документ')),
                ('page', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documents', to='page_generator.pagegenerator', verbose_name='Страница')),
            ],
        ),
    ]
