# Generated by Django 4.2 on 2024-06-05 20:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('page_generator', '0003_alter_navlinks_page_alter_pagegenerator_image_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Категория')),
            ],
            options={
                'verbose_name': 'Категория',
                'verbose_name_plural': 'Категории',
            },
        ),
        migrations.CreateModel(
            name='SubCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Подкатегория')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sub_categories', to='page_generator.category', verbose_name='Категория')),
            ],
            options={
                'verbose_name': 'Подкатегрия',
                'verbose_name_plural': 'Подкатегории',
            },
        ),
        migrations.CreateModel(
            name='Veteran',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100, verbose_name='Полное имя')),
                ('image', models.ImageField(upload_to='page-generator/veterans', verbose_name='Изображение')),
            ],
            options={
                'verbose_name': 'Ветеран',
                'verbose_name_plural': 'Ветераны',
            },
        ),
        migrations.AlterModelOptions(
            name='documents',
            options={'verbose_name': 'Документ', 'verbose_name_plural': 'Документы'},
        ),
        migrations.AlterModelOptions(
            name='pagegenerator',
            options={'verbose_name': 'Шаблон страниц', 'verbose_name_plural': 'Шаблоны страниц'},
        ),
        migrations.AddField(
            model_name='pagegenerator',
            name='title_en',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Заголовок'),
        ),
        migrations.AddField(
            model_name='pagegenerator',
            name='title_ky',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Заголовок'),
        ),
        migrations.AddField(
            model_name='pagegenerator',
            name='title_ru',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Заголовок'),
        ),
        migrations.AddField(
            model_name='person',
            name='full_name_en',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Полное имя человека'),
        ),
        migrations.AddField(
            model_name='person',
            name='full_name_ky',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Полное имя человека'),
        ),
        migrations.AddField(
            model_name='person',
            name='full_name_ru',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Полное имя человека'),
        ),
        migrations.AddField(
            model_name='person',
            name='position_en',
            field=models.TextField(blank=True, max_length=150, null=True, verbose_name='Должность человека'),
        ),
        migrations.AddField(
            model_name='person',
            name='position_ky',
            field=models.TextField(blank=True, max_length=150, null=True, verbose_name='Должность человека'),
        ),
        migrations.AddField(
            model_name='person',
            name='position_ru',
            field=models.TextField(blank=True, max_length=150, null=True, verbose_name='Должность человека'),
        ),
        migrations.AddField(
            model_name='table',
            name='name_en',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Имя таблицы'),
        ),
        migrations.AddField(
            model_name='table',
            name='name_ky',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Имя таблицы'),
        ),
        migrations.AddField(
            model_name='table',
            name='name_ru',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Имя таблицы'),
        ),
        migrations.AddField(
            model_name='tabledirectioncolumn',
            name='direction_en',
            field=models.TextField(max_length=200, null=True, verbose_name='Направление'),
        ),
        migrations.AddField(
            model_name='tabledirectioncolumn',
            name='direction_ky',
            field=models.TextField(max_length=200, null=True, verbose_name='Направление'),
        ),
        migrations.AddField(
            model_name='tabledirectioncolumn',
            name='direction_ru',
            field=models.TextField(max_length=200, null=True, verbose_name='Направление'),
        ),
        migrations.AddField(
            model_name='tabledirectioncolumn',
            name='status1_en',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='tabledirectioncolumn',
            name='status1_ky',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='tabledirectioncolumn',
            name='status1_ru',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='tabledirectioncolumn',
            name='status2_en',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='tabledirectioncolumn',
            name='status2_ky',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='tabledirectioncolumn',
            name='status2_ru',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.CreateModel(
            name='VeteranPosition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.CharField(blank=True, max_length=150, null=True, verbose_name='Должность')),
                ('veteran', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='veteran_positions', to='page_generator.veteran', verbose_name='Ветеран')),
            ],
        ),
        migrations.AddField(
            model_name='veteran',
            name='page',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='veterans', to='page_generator.pagegenerator', verbose_name='Страница'),
        ),
        migrations.CreateModel(
            name='SubSubCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Подкатегория 2')),
                ('subcategory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sub_sub_categories', to='page_generator.subcategory', verbose_name='Подкатегория')),
            ],
            options={
                'verbose_name': 'Подкатегория 2',
                'verbose_name_plural': 'Подкатегории 2',
            },
        ),
        migrations.AddField(
            model_name='pagegenerator',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='page_generator.category', verbose_name='Категория'),
        ),
        migrations.AddField(
            model_name='pagegenerator',
            name='subcategory',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='page_generator.subcategory', verbose_name='Подкатегория'),
        ),
        migrations.AddField(
            model_name='pagegenerator',
            name='subcategory2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='page_generator.subsubcategory', verbose_name='Подкатегория 2'),
        ),
    ]
