# Generated by Django 4.2 on 2024-06-06 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('page_generator', '0005_alter_person_options_remove_person_full_name_en_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='name_en',
            field=models.CharField(max_length=100, null=True, verbose_name='Категория'),
        ),
        migrations.AddField(
            model_name='category',
            name='name_ky',
            field=models.CharField(max_length=100, null=True, verbose_name='Категория'),
        ),
        migrations.AddField(
            model_name='category',
            name='name_ru',
            field=models.CharField(max_length=100, null=True, verbose_name='Категория'),
        ),
        migrations.AddField(
            model_name='documents',
            name='name_en',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Pdf Файл'),
        ),
        migrations.AddField(
            model_name='documents',
            name='name_ky',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Pdf Файл'),
        ),
        migrations.AddField(
            model_name='documents',
            name='name_ru',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Pdf Файл'),
        ),
        migrations.AddField(
            model_name='person',
            name='full_name_en',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Полное имя человека'),
        ),
        migrations.AddField(
            model_name='person',
            name='full_name_ky',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Полное имя человека'),
        ),
        migrations.AddField(
            model_name='person',
            name='full_name_ru',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Полное имя человека'),
        ),
        migrations.AddField(
            model_name='person',
            name='position_en',
            field=models.TextField(blank=True, max_length=150, null=True, verbose_name='Должность человека'),
        ),
        migrations.AddField(
            model_name='person',
            name='position_ky',
            field=models.TextField(blank=True, max_length=150, null=True, verbose_name='Должность человека'),
        ),
        migrations.AddField(
            model_name='person',
            name='position_ru',
            field=models.TextField(blank=True, max_length=150, null=True, verbose_name='Должность человека'),
        ),
    ]
