# Generated by Django 4.2 on 2024-06-06 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('page_generator', '0006_category_name_en_category_name_ky_category_name_ru_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='subcategory',
            name='name_en',
            field=models.CharField(max_length=100, null=True, verbose_name='Подкатегория'),
        ),
        migrations.AddField(
            model_name='subcategory',
            name='name_ky',
            field=models.CharField(max_length=100, null=True, verbose_name='Подкатегория'),
        ),
        migrations.AddField(
            model_name='subcategory',
            name='name_ru',
            field=models.CharField(max_length=100, null=True, verbose_name='Подкатегория'),
        ),
        migrations.AddField(
            model_name='subsubcategory',
            name='name_en',
            field=models.CharField(max_length=100, null=True, verbose_name='Подкатегория 2'),
        ),
        migrations.AddField(
            model_name='subsubcategory',
            name='name_ky',
            field=models.CharField(max_length=100, null=True, verbose_name='Подкатегория 2'),
        ),
        migrations.AddField(
            model_name='subsubcategory',
            name='name_ru',
            field=models.CharField(max_length=100, null=True, verbose_name='Подкатегория 2'),
        ),
    ]
