# Generated by Django 4.2 on 2024-06-07 10:14

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion
import utils.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Advertisements',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500, verbose_name='Оглавление')),
                ('title_ru', models.CharField(max_length=500, null=True, verbose_name='Оглавление')),
                ('title_en', models.CharField(max_length=500, null=True, verbose_name='Оглавление')),
                ('title_ky', models.CharField(max_length=500, null=True, verbose_name='Оглавление')),
                ('image', models.ImageField(upload_to='main/news/', verbose_name='Изображение')),
                ('text', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('text_ru', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('text_en', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('text_ky', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('date', models.DateField(verbose_name='Дата')),
            ],
            options={
                'verbose_name': 'Объявление',
                'verbose_name_plural': 'Объявления',
            },
        ),
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500, verbose_name='Оглавление')),
                ('title_ru', models.CharField(max_length=500, null=True, verbose_name='Оглавление')),
                ('title_en', models.CharField(max_length=500, null=True, verbose_name='Оглавление')),
                ('title_ky', models.CharField(max_length=500, null=True, verbose_name='Оглавление')),
                ('image', models.ImageField(upload_to='main/news/', verbose_name='Изображение')),
                ('text', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('text_ru', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('text_en', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('text_ky', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('date', models.DateField(verbose_name='Дата')),
            ],
            options={
                'verbose_name': 'Новость',
                'verbose_name_plural': 'Новости',
            },
        ),
        migrations.CreateModel(
            name='NewsImages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', utils.fields.WEBPField(upload_to=utils.fields.image_folder, verbose_name='Изображение')),
                ('news', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='data.news', verbose_name='Ссылка на новости')),
            ],
        ),
        migrations.CreateModel(
            name='AdvertisementsImages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', utils.fields.WEBPField(upload_to=utils.fields.image_folder, verbose_name='Изображение')),
                ('advertisement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='data.advertisements', verbose_name='Ссылка на объявления')),
            ],
        ),
    ]
