# Generated by Django 4.2 on 2024-06-06 15:27

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion
import utils.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MainPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500, verbose_name='Оглавление')),
                ('title_ru', models.CharField(max_length=500, null=True, verbose_name='Оглавление')),
                ('title_en', models.CharField(max_length=500, null=True, verbose_name='Оглавление')),
                ('title_ky', models.CharField(max_length=500, null=True, verbose_name='Оглавление')),
                ('image', models.ImageField(upload_to='main/news/', verbose_name='Изображение')),
                ('text', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('text_ru', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('text_en', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('text_ky', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('date', models.DateField(verbose_name='Дата')),
            ],
            options={
                'verbose_name': 'Новость',
                'verbose_name_plural': 'Новости',
            },
        ),
        migrations.CreateModel(
            name='Partners',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Имя/Название')),
                ('name_ru', models.CharField(max_length=50, null=True, verbose_name='Имя/Название')),
                ('name_en', models.CharField(max_length=50, null=True, verbose_name='Имя/Название')),
                ('name_ky', models.CharField(max_length=50, null=True, verbose_name='Имя/Название')),
                ('image', utils.fields.WEBPField(upload_to=utils.fields.image_folder)),
            ],
            options={
                'verbose_name': 'Партнер',
                'verbose_name_plural': 'Партнеры',
            },
        ),
        migrations.CreateModel(
            name='NewsImages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', utils.fields.WEBPField(upload_to=utils.fields.image_folder, verbose_name='Изображение')),
                ('news', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='main.news', verbose_name='Ссылка на новости')),
            ],
        ),
        migrations.CreateModel(
            name='BannerWithText',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=100, null=True, verbose_name='Описание Баннера')),
                ('title_ru', models.CharField(blank=True, max_length=100, null=True, verbose_name='Описание Баннера')),
                ('title_en', models.CharField(blank=True, max_length=100, null=True, verbose_name='Описание Баннера')),
                ('title_ky', models.CharField(blank=True, max_length=100, null=True, verbose_name='Описание Баннера')),
                ('image', models.ImageField(upload_to='main/', verbose_name='Изображение')),
                ('main', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='banner_texts', to='main.mainpage', verbose_name='Ссылка на главную страницу')),
            ],
        ),
    ]
