# Generated by Django 4.2 on 2024-06-07 08:41

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion
import utils.fields


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Advertisements',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500, verbose_name='Оглавление')),
                ('image', models.ImageField(upload_to='main/news/', verbose_name='Изображение')),
                ('text', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('date', models.DateField(verbose_name='Дата')),
            ],
            options={
                'verbose_name': 'Объявление',
                'verbose_name_plural': 'Объявления',
            },
        ),
        migrations.CreateModel(
            name='AdvertisementsImages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', utils.fields.WEBPField(upload_to=utils.fields.image_folder, verbose_name='Изображение')),
                ('advertisement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='main.advertisements', verbose_name='Ссылка на объявления')),
            ],
        ),
    ]
