# Generated by Django 4.2 on 2024-06-07 10:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_advertisements_advertisementsimages'),
    ]

    operations = [
        migrations.CreateModel(
            name='NavLinks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=100, null=True, verbose_name='Заголовок')),
                ('url', models.URLField(verbose_name='URL')),
                ('image', models.ImageField(upload_to='page-generator/', verbose_name='Изображение')),
            ],
            options={
                'verbose_name': 'Навигационные ссылки',
                'verbose_name_plural': 'Навигационные ссылки',
            },
        ),
        migrations.RemoveField(
            model_name='advertisementsimages',
            name='advertisement',
        ),
        migrations.RemoveField(
            model_name='newsimages',
            name='news',
        ),
        migrations.AlterModelOptions(
            name='mainpage',
            options={'verbose_name': 'Главная страница', 'verbose_name_plural': 'Главная страница'},
        ),
        migrations.AddField(
            model_name='mainpage',
            name='description',
            field=models.TextField(blank=True, max_length=150, null=True, verbose_name='Описание'),
        ),
        migrations.AddField(
            model_name='partners',
            name='link',
            field=models.URLField(default='https://google.com', verbose_name='Ссылка на сайт'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='partners',
            name='page',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='partners', to='main.mainpage', verbose_name='Ссылка на главную страницу'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Advertisements',
        ),
        migrations.DeleteModel(
            name='AdvertisementsImages',
        ),
        migrations.DeleteModel(
            name='News',
        ),
        migrations.DeleteModel(
            name='NewsImages',
        ),
        migrations.AddField(
            model_name='navlinks',
            name='page',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='nav_links', to='main.mainpage', verbose_name='Страница'),
        ),
    ]
